version: '3.8'

services:
  comp:
    container_name: c-reactjs-comp
    build:
      context: ./
    environment:
      - REACT_APP_API_END_POINT=http://localhost:3001
    ports:
      - '80:80'
    image: c-reactjs-comp